version: '3.8'

services:
  payment:
    build:
      context: ./payment
      args:
        - NS=172.28.0.15
    networks:
      reference:
        ipv4_address: 172.28.0.11
  lareference:
    build: 
      context: ./lareference
      args:
        - NS=172.28.0.15
    networks:
      reference:
        ipv4_address: 172.28.0.10
  dns:
    build:
      context: ./dns
    networks:
      reference:
        ipv4_address: 172.28.0.15
    privileged: true
    command: /bin/sh -c "nginx;tail -f /var/log/nginx/*.log;"

networks:
  reference:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1 

        